### ISSUE TITLE
Errors importing from pytextrank 

### ISSUE THREAD

**Issue by Erin59** [DerwenAI/pytextrank#42]
Hi! I'm working on a project connected with NLP and was happy to find out that there is such a tool as PyTextRank. However, I've encountered an issue at the very beginning trying to just import package to run the example code given [here](https://github.com/DerwenAI/pytextrank/wiki/Example-Usage:-version-1.x). 
The error that I get is the following:
```
----> from pytextrank import json_iter, parse_doc, pretty_print
ImportError: cannot import name 'json_iter'
----> from pytextrank import parse_doc
ImportError: cannot import name 'parse_doc'
```
I've tried running it in iPython console and a Jupyter Notebook, both the same result. I've installed PyTextRank with pip, the python version that I have is 3.5.4., spacy 2.1.8., networkx 2.4, graphvis 0.13.2

**Comment by ceteri** [comment]
Have you tried working with the 2.0.0 release?

See the code samples in [`example.py`](https://github.com/DerwenAI/pytextrank/blob/master/example.py) which is quite different from version 1.x -- and does not use those imported functions.

**Comment by Erin59** [comment]
I've downloaded the git repo and tried to run the example.py, got another error instead:
```
$ python example.py                                                                                                     Traceback (most recent call last):
  File "example.py", line 33, in <module>
    doc = nlp(text)
  File "C:\Users\Anastasia\AppData\Local\Programs\Python\Python35\lib\site-packages\spacy\language.py", line 402, in __call__    doc = proc(doc, **component_cfg.get(name, {}))
  File "C:\Users\Anastasia\Downloads\pytextrank-master\pytextrank-master\pytextrank\pytextrank.py", line 532, in PipelineComponent
    Doc.set_extension("phrases", force=True, default=self.calc_textrank())  File "C:\Users\Anastasia\Downloads\pytextrank-master\pytextrank-master\pytextrank\pytextrank.py", line 391, in calc_textrank
    self.collect_phrases(chunk)
  File "C:\Users\Anastasia\Downloads\pytextrank-master\pytextrank-master\pytextrank\pytextrank.py", line 347, in collect_phrases    rank = self.ranks[node_id]
KeyError: 20
```
Will try to downgrade spacy now and update how it goes.

**Comment by Erin59** [comment]
Okay, downgraded spacy to 2.0.0, the KeyError from above still. Also, the import error remains too.

**Comment by ceteri** [comment]
Were you attempting to use sample code for PyTextRank 1.x with an installation of the most recent PyTextRank (v2.0.0) ?

That won't work, regardless of which version of spaCy is being used. The imports fail because those functions no longer exist.

Best next steps if you want to use spaCy 2.x are:

- get rid of the code that includes `from pytextrank import json_iter, parse_doc, pretty_print`
- install the latest PyTextRank
- use the code shown in `example.py`

**Comment by neomatrix369** [comment]
Hey @ceteri I get the same error and I have checked the current version of `pytextrank` on my system:

```
$ pip list | grep pytext
pytextrank         2.0.0 
```
You can have a look at this kernek/notebook to see what's happening:
- [Jupyter Notebook](https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/better-nlp/notebooks/jupyter/better_nlp_summarisers.ipynb) ([Code](https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/better-nlp/library/org/neomatrix369/summariser_pytextrank.py)]
- [Kernel](https://www.kaggle.com/neomatrix369/better-nlp-summarisers-notebook) ([Code](https://www.kaggle.com/neomatrix369/summariser-pytextrank-class))

**Comment by ceteri** [comment]
Hi @neomatrix369 , we seem to have resolved that in release `2.0.1` now available on <https://pypi.org/project/pytextrank/> (via pip or conda)

That's related to #47, #56 
Unless there's a new issue?

**Comment by neomatrix369** [comment]
> Hi @neomatrix369 , we seem to have resolved that in release `2.0.1` now available on https://pypi.org/project/pytextrank/ (via pip or conda)
> 
> That's related to #47, #56
> Unless there's a new issue?

I tried this and you can revisit the links above (https://github.com/DerwenAI/pytextrank/issues/42#issuecomment-596663590) the issue hasn't gone away.

**Comment by neomatrix369** [comment]
@ceteri Any update on the above? I still have this issue not just local machine but on Kaggle as well.

**Comment by neomatrix369** [comment]
@ceteri Would you like me to open an issue on this so it can be actively looked into? Would be nice to get behind what causes this issue.

Thanks!
